---
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## About Me

Hi y'all! My name is Justin and I'm originally from Durham, NC but now live in Baltimore. 

My undergraduate academic training was in civil engineering, sociology, French, and my graduate academic training was in urban planning. I have also worked as a community organizer and data analyst. I am currently a PhD student in health and public policy, within the Department of Health Policy and Management at JHSPH. A lot of my research focuses on how housing policy and interventions in the built environment can reduce injuries and violence. I've been doing statistical analysis on a semi-regular basis for the past 2-3 years and using R for the past year or so. I'm excited to diversify and deepen my R skills this term! 

## Fun Facts

Some fun facts about me: 

- I just got married! 
- I am part French and try to visit family there as often as I can.
- My partner and I recently bought into a cooperative apartment building in Charles Village.
- I worked for the City of Baltimore during a mayoral scandal, ransomware attack, and pandemic.

## Cool Link

Check out this [interactive housing and community development map](https://cels.baltimorehousing.org/codemapv2/) for Baltimore City.
